### PR TITLE
Simplify and Improve TTRenderer

### PR DESCRIPTION
**Pull request by holenet**
## Selection
There are three selection modes.
1. Without any key: select blocks regardless of old state.
2. With ctrl key: unselect blocks regardless of old state.
3. With shift key: toggle blocks' selections

Also, selecting whole table, some columns/rows is available.
And, some color schemes were changed.

image

image

**Note**: I think current canvas is fast enough. But if you want to improve the performance, please let me know. I'll make more optimizations.

### CODE REVIEW

**Comment by holenet** [comment]
image

I added a tip popup.

**Comment by Tommybro** [comment]
I think there need to be tip about block selecting without any key, whole selecting, whole unselecting, line selecting

**Comment by Tommybro** [comment]
And I think line selecting should be line toggling

**Comment by holenet** [comment]
@Tommybro 
I cannot make a tip message which is quiet simple but also demonstrative enough.
Could you make an example of the tip message?

And, I think line selecting does not have to be in toggle mode without any key.

**Comment by holenet** [comment]
image

I modified the tip message.

**Comment by holenet** [comment]
image

I modified the tip message.

**Pull request merged**
