### PR TITLE
All implementation about Evaluation

### PR DESCRIPTION
**Pull request by Tommybro**
Show lecture ratings when search Lecture
Show lecture rating and evaluations when click lecture Info
Can evaluate lecture
Can delete my evaluation
Can modify my evaluation
Can Like or dislike other people's evaluation

### CODE REVIEW

**Comment by Tommybro** [comment]
I add some screenshots

image
image

**Comment by Tommybro** [comment]
image

**Comment by Tommybro** [comment]
image

**Comment by Tommybro** [comment]
Now can get receiver name when click send icon, but as one button can't have two popup, removed previous popup(message)

**Comment by holenet** [comment]
@Tommybro 
I think we can attach multiple Popups to one component with implementing nested Popups.
That means, a Popup has another Popup as the trigger attribute.
And the inner Popup has the button as the trigger.

I think this would work well. Please give it a try.

**Comment by holenet** [comment]
Could you make delete confirm popup on the delete button of the timetable like send button?

**Comment by holenet** [comment]
Or, using _Confirm_ semantic component seems good.

**Comment by Tommybro** [comment]
OK I'll try

**Comment by Tommybro** [comment]
Did what @holenet said
image

**Pull request merged**
