### PR TITLE
Error Handling Simplification & Bug Fixes & Enhancement

### PR DESCRIPTION
**Pull request by holenet**
# Error Handling Simplification
- Error handling at `SignUp`, `SettingsTab` and `SignIn` becomes simpler than before.
- Both custom errors and backend errors are treated as the props of the component and modified by redux action and reducer.
- By Introducing `Notice` Component, the modularity has increased.

# Several Bug Fixes
**Resolved Bug List**
- Cannot create my timetable by `AddLecture`.
- Added a lecture to a `BookmarkedTimetable`, but actually did not.
- Cannot Add lecture on `ReceiveTab`.
- `Department` List and `Major` List does not changed when College index was changed in the `SignUp` and `SettingsTab`.
- Updated profile with `department` or `major` null, but it ignored.
- Previous error state is not reset even if the related component is unmounted before.
- When a `LecturePopup` component just has opened up, the rating is shown as `Nan` until the right data is received by saga.
- The page of the `SearchLecture` is not reset even when searching with different query.

# Enhancement
When a user signed up just before, the success `Notice` is shown for several seconds with a message;

> You have successfully joined the membership.
Return to sign in page...

After that, the page would be redirected to `SignIn` page automatically.

### CODE REVIEW

**Comment by Tommybro** [comment]
When user sign in, message "You have joined ~" appears.
I think it will be good to show this kind of message when user modify user info in settings tab.

**Comment by holenet** [comment]
@Tommybro
There are default message props for `Notice`.
Please refer to the file `Notice/index.js`.

**Comment by Tommybro** [comment]
Ah OK

**Comment by Tommybro** [comment]
Did you solve this bug?
`Added a lecture to a BookmarkedTimetable, but actually did not.`

**Pull request merged**
